$ANSIBLE_VAULT;1.1;AES256
61366435313435383334373531303236653562353136376463316365366136353330366561313761
3736353031363736373835333265636532646566626132660a313832653531323065313237326536
61353333306262353661396635323862376362353038393332313737616231323135653961343764
3965353537336134330a613038363262386433343133373966353231623666616337643039313430
36356637623634333037656630643334333231343438356536626664386634643238383562653665
66333365346133383634643433383532323563616165633237633034656665633937633132613566
64303839393532653430316630363131323365643265396431373363646364333165626632373066
33346538323736303463623532623132393339333032353838323732343465373034626363366365
38383733656261306662313563393730343330393362333239666365616638623164373538393166
36623061336433366538336462363264323532333137366462323836393131666166373238616464
34303966616538336235383830656231356564313530333739656438633036336430653264623636
63383630623132663965343535333635633439383564626362333163343462663032633235306430
38393235366565646265613264343330643963376265663066373231336135356430363539383330
32663061393831313564633937613166393537396463333164373838396637316661373834303830
32636638396231363962326232343831366663343639636235363735333863666633633830666439
3239
