name: Python CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop, lab03 ]
  pull_request:
    branches: [ main, master, develop ]

env:
  PYTHON_VERSION: '3.11'
  WORKING_DIRECTORY: ./app_python

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Test with pytest
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        pytest tests/ -v --cov=app --cov-report=term

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Run Snyk
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=app_python/requirements.txt --severity-threshold=high
      continue-on-error: true

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/lab03'
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Generate CalVer tags
      id: version
      run: |
        FULL_DATE=$(date -u +'%Y.%m.%d')
        MONTH=$(date -u +'%Y.%m')
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "full_date=${FULL_DATE}" >> $GITHUB_OUTPUT
        echo "month=${MONTH}" >> $GITHUB_OUTPUT
        echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "tags=aliyasag/devops-info-service:${FULL_DATE},aliyasag/devops-info-service:${MONTH},aliyasag/devops-info-service:latest,aliyasag/devops-info-service:${SHORT_SHA}" >> $GITHUB_OUTPUT
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./app_python
        file: ./app_python/Dockerfile
        push: true
        tags: ${{ steps.version.outputs.tags }}